### PR TITLE
Update read.md to include more distros and invites to Discord/Matrix

### PR DESCRIPTION
**Pull request by udekmp**
ChimeraOS and openSUSE Kalpa added as distros.  Added invites for openSUSE MicroOS, VanillaOS, and ChimeraOS.

### CODE REVIEW

**Comment by Dvlv** [comment]
Looks like something has gone wrong here, the diff seems to think you have changed almost every line.

I can pick out the things you mentioned in the description separately, or would you like to submit a new PR?

**Comment by udekmp** [comment]
> Looks like something has gone wrong here, the diff seems to think you have changed almost every line.
> 
> I can pick out the things you mentioned in the description separately, or would you like to submit a new PR?

Sorry for the late reply.  Yeah I am really bad at pull requests, sorry about that. Thank you.

**Comment by udekmp** [comment]
this is all i changed:

Distros

- [openSUSE Aeon](https://aeondesktop.org) - a variant of openSUSE Tumbleweed providing an immutable GNOME desktop featuring containers with Distrobox.
- [openSUSE Kalpa](https://en.opensuse.org/Portal:Kalpa) - Similar to openSUSE Aeon, but based on KDE.

## Discussion

  - [VanillaOS Discord](https://discord.gg/vanilla-os-1023243680829681704)
  - [ChimeraOS Discord](https://discord.gg/rgB8utyteK)

- Matrix Rooms:
  - openSUSE MicroOS/Aeon/Kalpa Matrix Room](https://matrix.to/#/#microos-desktop:opensuse.org)

**Comment by Dvlv** [comment]
Thanks, I've added those links!

**Pull request closed without merging**
